<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
  <!-- Define properties for dimensions -->
  <xacro:property name="stator_size" value="0.102" />  <!-- Maintain cube form -->
  <xacro:property name="rotor_height" value="0.008" /> <!-- Thinner disk -->
  <xacro:property name="rotor_radius" value="0.020" /> <!-- Smaller radius -->
  <xacro:property name="angle_length" value="0.020" />
  <xacro:property name="angle_width" value="0.002" />
  <xacro:property name="angle_height" value="0.002" />

  <!-- Define the qube model macro -->
  <xacro:macro name="qube" params="prefix:=''">
    <!-- Base link - no geometry -->
    <link name="${prefix}base_link"/>

    <!-- Stator link - black cube -->
    <link name="${prefix}stator_link">
      <visual>
        <geometry>
          <box size="${stator_size} ${stator_size} ${stator_size}"/>
        </geometry>
        <material name="black">
          <color rgba="0 0 0 1"/>
        </material>
      </visual>
      <collision>
        <geometry>
          <box size="${stator_size} ${stator_size} ${stator_size}"/>
        </geometry>
      </collision>
      <inertial>
        <mass value="0.5"/>
        <inertia ixx="0.001" ixy="0" ixz="0" iyy="0.001" iyz="0" izz="0.001"/>
      </inertial>
    </link>

    <!-- Rotor link - smaller red cylinder -->
    <link name="${prefix}rotary_link">
      <visual>
        <geometry>
          <cylinder length="${rotor_height}" radius="${rotor_radius}"/>
        </geometry>
        <material name="red">
          <color rgba="1 0 0 1"/>
        </material>
      </visual>
      <collision>
        <geometry>
          <cylinder length="${rotor_height}" radius="${rotor_radius}"/>
        </geometry>
      </collision>
      <inertial>
        <mass value="0.1"/>
        <inertia ixx="0.0001" ixy="0" ixz="0" iyy="0.0001" iyz="0" izz="0.0002"/>
      </inertial>
    </link>

    <!-- Angle link - white box -->
    <link name="${prefix}indicator_link">
      <visual>
        <geometry>
          <box size="${angle_length} ${angle_width} ${angle_height}"/>
        </geometry>
        <material name="white">
          <color rgba="1 1 1 1"/>
        </material>
      </visual>
      <collision>
        <geometry>
          <box size="${angle_length} ${angle_width} ${angle_height}"/>
        </geometry>
      </collision>
      <inertial>
        <mass value="0.01"/>
        <inertia ixx="0.00001" ixy="0" ixz="0" iyy="0.00001" iyz="0" izz="0.00001"/>
      </inertial>
    </link>

    <!-- Fixed joint connecting base_link to stator_link -->
    <joint name="${prefix}stator_joint" type="fixed">
      <parent link="${prefix}base_link"/>
      <child link="${prefix}stator_link"/>
      <origin xyz="0 0 ${stator_size/2}" rpy="0 0 0"/>
    </joint>

    <!-- Revolute joint connecting stator_link to rotor_link -->
    <joint name="${prefix}rotary_joint" type="continuous">
      <parent link="${prefix}stator_link"/>
      <child link="${prefix}rotary_link"/>
      <origin xyz="0 0 ${stator_size/2 + rotor_height/2}" rpy="0 0 0"/>
      <axis xyz="0 0 1"/>  <!-- Rotate around Z axis -->
    </joint>

    <!-- Fixed joint connecting rotor_link to indicator_link -->
    <joint name="${prefix}indicator_joint" type="fixed">
      <parent link="${prefix}rotary_link"/>
      <child link="${prefix}indicator_link"/>
      <origin xyz="${angle_length/2} 0 ${rotor_height/2 + 0.001}" rpy="0 0 0"/>
    </joint>
  </xacro:macro>
</robot>
