controller_manager:
  ros__parameters:
    update_rate: 100  # Hz
    
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
    
    velocity_controller:
      type: velocity_controllers/JointGroupVelocityController

joint_state_broadcaster:
  ros__parameters: {}

velocity_controller:
  ros__parameters:
    joints:
      - motor_joint  # THIS MUST MATCH THE HARDWARE INTERFACE NAME
    command_interface: velocity
